title: AqualinkD
description: Daemon to control Jandy Aqualink RS (and other) pool equipment from any home automations hub (Alexa, Homekit, Home Assistant, smartthings, domoticz etc) or web browser.

defaults:
  - scope:
      path: ""
    values:
      image: /web/aqualinkd.png
      
plugins:
  - jekyll-seo-tag
 
